### ISSUE TITLE
Interaction of Create/VS/Clockwork and JSG

### ISSUE THREAD

**Issue by Acetonerer** [Tau-ri-Dev/Mod-JSG-1.20.x#50]
Hi,

I'm experiencing a crash when using JustStargateMod (JSG) mods together with the Valkyrien Skies and Clockwork. Specifically, the game crashes when I try to assemble Stargate on a platform that has its own physics enabled by these mods. 

Here are the details:
- Valkyrien Skies version: 2.3.0-beta.5
- Clockwork version: 1.20.1-0.1.16-forge-b3b22e39fe
- Architectury: 9.2.14
- Kotlin Fro Forge: 4.5.0
- JustStargateMod version: 5.0.3.1-Beta
- Minecraft version: 1.20.1

Crash log snippet:
java.lang.ArrayIndexOutOfBoundsException: Index 4194596 out of bounds for length 315
	at net.minecraft.world.level.levelgen.Aquifer$NoiseBasedAquifer.m_188445_(Aquifer.java:497)

The crash seems to happen when the physics for the platform are activated and I attempt to assemble the Stargate. 
I guess when the physics engine is activated (the platform becomes mobile), the JSG mod cannot correctly determine the coordinates of the blocks or manage the objects.
[crash-2024-07-21_13.16.26-server.txt](https://github.com/user-attachments/files/16323298/crash-2024-07-21_13.16.26-server.txt)

Thank you for your help!

Best regards,
Alex

**Comment by Fredyman95** [comment]
Well its actualy right - because address system is based on x y z of baseblock if stargate - when you move it without unmarge gate - gate will have more addreses

**Comment by Acetonerer** [comment]
Okay, my next question might seem stupid (it really is, I think), but even if we assume that the assembled ship from VS can freely move in space, wouldn't each of its points have x y z coordinates, albeit with a few decimal places?

I mean, even if we assume that the gates on the assembled ship are also assembled (let's take gate_1 as the gate on the ship and gate_2 as the gate on the stationary base), and as the ship moves through space the address of gate_1 can constantly change, while gate_2 remains static, wouldn't that make traveling from gate_1 to gate_2 impossible? (and from gate_2 to gate_1 without updating the address of gate_1 indeed not possible)

And even if we assume that building gates on the assembled ship would be possible, how difficult would it be to implement dynamic coordinate changes for the gates?

Thank you in advance for your attention to my amateur questions :D

**Comment by Fredyman95** [comment]
We already tried that with different mod on 1.12.2 but it caused more cons then pros. Basicly gate states werent updated. So its hard. Also from some research of VS - this mod doesnt work well on servers as well... I know that it will be great to have gate here but its not possible - at least not now or nearest future.

**Comment by TheidenHD** [comment]
I have experimented with this setup in the past. 

1. The crash has something to do with the World generation. Valkyrien Skies places those Ships somewhere way outside the World. When the Gate calculates the Temperature, it checks the blocks around itself. Somewhere in this process, something doesn't work correctly and it's trying to generate some chunks there which crashes the World generation. This can be (temporarily) fixed by using a different world generation Algorithm. Superflat worlds work and some world gen Mods also work.
2. The DHD doesn't correctly recognize its position and rotation. It gets pleased wrong, The back (for changing the upgrades) changes and you can't select the Symbols.
3. Dialing the Gate often fails, it works rarely with the DHD but flawlessly with the Admin tool.

All in all, technical problems should be easily fixable. I know it is not a Priority, but the idea of having working Stargates on flying Ships is exciting.

**Comment by Fredyman95** [comment]
> I have experimented with this setup in the past.
> 
> 1. The crash has something to do with the World generation. Valkyrien Skies places those Ships somewhere way outside the World. When the Gate calculates the Temperature, it checks the blocks around itself. Somewhere in this process, something doesn't work correctly and it's trying to generate some chunks there which crashes the World generation. This can be (temporarily) fixed by using a different world generation Algorithm. Superflat worlds work and some world gen Mods also work.
> 2. The DHD doesn't correctly recognize its position and rotation. It gets pleased wrong, The back (for changing the upgrades) changes and you can't select the Symbols.
> 3. Dialing the Gate often fails, it works rarely with the DHD but flawlessly with the Admin tool.
> 
> All in all, technical problems should be easily fixable. I know it is not a Priority, but the idea of having working Stargates on flying Ships is exciting.

Hello,

It is looking that you still not understand how JSG works - so again address of gate is based on base block position in world - **ON CORDINATED X Y Z** so everytime you **move merged ** gate (or even just placed base block) this gate get **NEW** address!

We already tried to solve this issue and make compatibility with space mod that have same mechanic on 1.12.2 - without success. It only caused bugs like not closing gates, changing address of gates after every update...

And before you say anything - I just test test this mod - you dont just move in world forward, backward, left, right up and down, but you can also move diagonally.... and all this movement is in world - **with CHANGING X Y Z coordinates!**

So that will cause not just one problem but thousand of problems...

I can say that VS cant be compatible with JSG.

**Comment by TheidenHD** [comment]
I know how JSG  handles coordinates, but I think you have a misconception about how VS handles coordinates. The Blocks used in the Ships are stored a couple of million blocks away in the [Shipyard](https://wiki.valkyrienskies.org/wiki/FAQ#Where_are_the_blocks_of_the_ship_stored?). The Mod then Projekts the Ship into the World. that also means when the Ship is moved the coordinates from the Stargate don't change. You can see that if you lock at the block with F3 while moving the Ship. The only real problems occur when you build the Gate in the world and turn it into a Ship or if you build it onto a Ship and place it back in the world.
